# Generated by Django 5.2 on 2026-01-12 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anagraphic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('contact_email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anagraphic',
                'db_table_comment': 'Ogni utente registrato (anagraphic) può essere anche un autore, ma non è obbligatorio.\t\t\nOgni autore (author) può essere un utente registrato, ma può anche essere una persona esterna al sistema.\t\t\nIl rapporto tra le due tabelle è quindi uno a uno opzionale (1:1 opzionale)\t\t\n',
            },
        ),
        migrations.CreateModel(
            name='ArchaeologicalEvidenceTypology',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_typology_archaeological_evidence', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archaeological_evidence_typology',
            },
        ),
        migrations.CreateModel(
            name='BaseMap',
            fields=[
                ('desc_base_map', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'base_map',
            },
        ),
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('title', models.CharField(blank=True, null=True)),
                ('author', models.CharField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, db_column='DOI', null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bibliography',
            },
        ),
        migrations.CreateModel(
            name='Chronology',
            fields=[
                ('chronological_period', models.CharField(blank=True, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chronology',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name_country', models.CharField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='FirstDiscoveryMethod',
            fields=[
                ('desc_first_discovery_method', models.CharField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'first_discovery_method',
            },
        ),
        migrations.CreateModel(
            name='FunctionalClass',
            fields=[
                ('desc_functional_class', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'functional_class',
            },
        ),
        migrations.CreateModel(
            name='ImageScale',
            fields=[
                ('desc_image_scale', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'image_scale',
            },
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('desc_image_type', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'image_type',
            },
        ),
        migrations.CreateModel(
            name='IntepretationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interpretation', models.IntegerField(blank=True, null=True)),
                ('id_author', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intepretation_author',
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investigation',
            },
        ),
        migrations.CreateModel(
            name='InvestigationType',
            fields=[
                ('desc_investigation_type', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'investigation_type',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('denominazione_comune', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sigla_provincia', models.CharField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'municipality',
            },
        ),
        migrations.CreateModel(
            name='Physiography',
            fields=[
                ('desc_physiography', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'physiography',
            },
        ),
        migrations.CreateModel(
            name='PositionalAccuracy',
            fields=[
                ('degree', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position_type', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'positional_accuracy',
            },
        ),
        migrations.CreateModel(
            name='PositioningMode',
            fields=[
                ('desc_positioning_mode', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'positioning_mode',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla_provincia', models.TextField(blank=True, null=True)),
                ('denominazione_provincia', models.TextField(blank=True, null=True)),
                ('superficie_kmq', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('codice_sovracomunale', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('ripartizione_geografica', models.TextField(blank=True, null=True)),
                ('codice_regione', models.TextField(blank=True, null=True)),
                ('denominazione_regione', models.TextField(blank=True, null=True)),
                ('tipologia_regione', models.TextField(blank=True, null=True)),
                ('superficie_kmq', models.TextField(blank=True, null=True)),
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='SourcesType',
            fields=[
                ('desc_sources_type', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sources_type',
            },
        ),
        migrations.CreateModel(
            name='Typology',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_typology', models.TextField(blank=True, null=True)),
                ('id_functional_class', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'typology',
                'db_table_comment': 'tabella relativa alle tipologie di sito associate alle classi funzionali principali',
            },
        ),
        migrations.CreateModel(
            name='ArchaeologicalEvidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('evidence_name', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('additional_topography', models.TextField(blank=True, null=True)),
                ('locality_name', models.CharField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('chronology_certainty_level', models.IntegerField(blank=True, db_column='chronology_certainty_level', default=1, null=True)),
                ('geometry', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('id_archaeological_evidence_typology', models.ForeignKey(blank=True, db_column='id_archaeological_evidence_typology', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.archaeologicalevidencetypology')),
                ('id_base_map', models.ForeignKey(blank=True, db_column='id_base_map', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.basemap')),
                ('id_chronology', models.ForeignKey(blank=True, db_column='id_chronology', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.chronology')),
                ('id_country', models.ForeignKey(blank=True, db_column='id_country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.country')),
                ('id_first_discovery_method', models.ForeignKey(db_column='id_first_discovery_method', on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.firstdiscoverymethod')),
                ('id_investigation', models.ForeignKey(blank=True, db_column='id_investigation', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.investigation')),
                ('id_municipality', models.ForeignKey(blank=True, db_column='id_municipality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.municipality')),
                ('id_physiography', models.ForeignKey(blank=True, db_column='id_physiography', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.physiography')),
                ('id_positional_accuracy', models.ForeignKey(db_column='id_positional_accuracy', on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.positionalaccuracy')),
                ('id_positioning_mode', models.ForeignKey(db_column='id_positioning_mode', on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.positioningmode')),
                ('id_province', models.ForeignKey(blank=True, db_column='id_province', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.province')),
                ('id_region', models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.region')),
            ],
            options={
                'db_table': 'archaeological_evidence',
            },
        ),
        migrations.CreateModel(
            name='ArchEvRelatedDoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('id_archaeological_evidence', models.ForeignKey(blank=True, db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.archaeologicalevidence')),
            ],
            options={
                'db_table': 'arch_ev_related_doc',
            },
        ),
        migrations.CreateModel(
            name='ArchEvResearch',
            fields=[
                ('id_research', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_archaeological_evidence', models.ForeignKey(blank=True, db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.archaeologicalevidence')),
            ],
            options={
                'db_table': 'arch_ev_research',
            },
        ),
        migrations.CreateModel(
            name='ArchEvBiblio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_archaeological_evidence', models.ForeignKey(blank=True, db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.archaeologicalevidence')),
                ('id_bibliography', models.ForeignKey(blank=True, db_column='id_bibliography', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.bibliography')),
            ],
            options={
                'db_table': 'arch_ev_biblio',
            },
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('chronology_certainty_level', models.IntegerField(blank=True, db_column='chronology_certainty_level', default=1, null=True)),
                ('id_chronology', models.ForeignKey(blank=True, db_column='id_chronology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.chronology')),
                ('id_functional_class', models.ForeignKey(blank=True, db_column='id_functional_class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.functionalclass')),
            ],
            options={
                'db_table': 'interpretation',
                'db_table_comment': 'Qui vengono raccolte le diverse interpretazioni date al sito (in merito alla sua classe funzionale e alla tipologia) proposte dai diversi ricercatori',
            },
        ),
        migrations.CreateModel(
            name='InterpretationBibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bibliography', models.ForeignKey(blank=True, db_column='id_bibliography', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.bibliography')),
                ('id_interpretation', models.ForeignKey(blank=True, db_column='id_interpretation', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.interpretation')),
            ],
            options={
                'db_table': 'interpretation_bibliography',
            },
        ),
        migrations.AddField(
            model_name='investigation',
            name='id_investigation_type',
            field=models.ForeignKey(blank=True, db_column='id_investigation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.investigationtype'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='id_province',
            field=models.ForeignKey(blank=True, db_column='id_province', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.province'),
        ),
        migrations.AddField(
            model_name='province',
            name='codice_regione',
            field=models.ForeignKey(db_column='codice_regione', on_delete=django.db.models.deletion.CASCADE, to='frontend.region'),
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('title', models.CharField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('keywords', models.CharField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, null=True)),
                ('geometry', models.CharField()),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_environment_relationship', models.TextField(blank=True, null=True)),
                ('additional_topography', models.TextField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('locality_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geometry', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('id_base_map', models.ForeignKey(blank=True, db_column='id_base_map', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.basemap')),
                ('id_country', models.ForeignKey(blank=True, db_column='id_country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.country')),
                ('id_first_discovery_method', models.ForeignKey(blank=True, db_column='id_first_discovery_method', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.firstdiscoverymethod')),
                ('id_municipality', models.ForeignKey(blank=True, db_column='id_municipality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.municipality')),
                ('id_physiography', models.ForeignKey(blank=True, db_column='id_physiography', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.physiography')),
                ('id_positional_accuracy', models.ForeignKey(blank=True, db_column='id_positional_accuracy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.positionalaccuracy')),
                ('id_positioning_mode', models.ForeignKey(blank=True, db_column='id_positioning_mode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.positioningmode')),
                ('id_province', models.ForeignKey(blank=True, db_column='id_province', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.province')),
                ('id_region', models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.region')),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.AddField(
            model_name='interpretation',
            name='id_site',
            field=models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('file_name', models.TextField(blank=True, null=True)),
                ('acquisition_date', models.TextField(blank=True, null=True)),
                ('desc_image', models.TextField(blank=True, null=True)),
                ('id_image_scale', models.IntegerField(blank=True, null=True)),
                ('id_image_type', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_anagraphic', models.IntegerField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('projection', models.TextField(blank=True, null=True)),
                ('spatial_resolution', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('key_words', models.TextField(blank=True, null=True)),
                ('id_archaeological_evidence', models.ForeignKey(blank=True, db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.archaeologicalevidence')),
                ('id_site', models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='SiteArchEvidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_archaeological_evidence', models.ForeignKey(db_column='id_archaeological_evidence', on_delete=django.db.models.deletion.CASCADE, to='frontend.archaeologicalevidence')),
                ('id_site', models.ForeignKey(db_column='id_site', on_delete=django.db.models.deletion.CASCADE, to='frontend.site')),
            ],
            options={
                'db_table': 'site_arch_evidence',
                'db_table_comment': 'Tabella che implementa la relazione 0,n a 0,n tra sito e evidenza archeologica.',
            },
        ),
        migrations.CreateModel(
            name='SiteBibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bibliography', models.ForeignKey(blank=True, db_column='id_bibliography', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.bibliography')),
                ('id_site', models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site')),
            ],
            options={
                'db_table': 'site_bibliography',
            },
        ),
        migrations.CreateModel(
            name='SiteInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_investigation', models.ForeignKey(blank=True, db_column='id_investigation', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.investigation')),
                ('id_site', models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site')),
            ],
            options={
                'db_table': 'site_investigation',
            },
        ),
        migrations.CreateModel(
            name='SiteRelatedDocumentation',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_site', models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site')),
            ],
            options={
                'db_table': 'site_related_documentation',
            },
        ),
        migrations.CreateModel(
            name='SiteToponymy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancient_place_name', models.TextField(blank=True, null=True)),
                ('contemporary_place_name', models.TextField(blank=True, null=True)),
                ('id_site', models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site')),
            ],
            options={
                'db_table': 'site_toponymy',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('name', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_chronology', models.ForeignKey(blank=True, db_column='id_chronology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.chronology')),
                ('id_sources_typology', models.ForeignKey(blank=True, db_column='id_sources_typology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.sourcestype')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='SiteSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_site', models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site')),
                ('id_sources', models.ForeignKey(db_column='id_sources', on_delete=django.db.models.deletion.CASCADE, to='frontend.sources')),
            ],
            options={
                'db_table': 'site_sources',
            },
        ),
        migrations.CreateModel(
            name='ArchEvSources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_archaeological_evidence', models.ForeignKey(blank=True, db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.archaeologicalevidence')),
                ('id_sources', models.ForeignKey(db_column='id_sources', on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.sources')),
            ],
            options={
                'db_table': 'arch_ev_sources',
            },
        ),
        migrations.AddField(
            model_name='interpretation',
            name='id_typology',
            field=models.ForeignKey(blank=True, db_column='id_typology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.typology'),
        ),
        migrations.CreateModel(
            name='TypologyDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_typology_detail', models.TextField(blank=True, null=True)),
                ('id_typology', models.IntegerField(blank=True, null=True)),
                ('id_functional_class', models.ForeignKey(blank=True, db_column='id_functional_class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.functionalclass')),
            ],
            options={
                'db_table': 'typology_detail',
            },
        ),
        migrations.AddField(
            model_name='interpretation',
            name='id_typology_detail',
            field=models.ForeignKey(blank=True, db_column='id_typology_detail', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.typologydetail'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255)),
                ('view_name', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'db_table': 'access_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='access_log_timesta_f9acc6_idx'), models.Index(fields=['user', '-timestamp'], name='access_log_user_id_3072cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], max_length=10)),
                ('model_name', models.CharField(help_text='Name of the model that was modified', max_length=100)),
                ('object_id', models.CharField(help_text='ID of the object that was modified', max_length=255)),
                ('object_str', models.CharField(blank=True, help_text='String representation of the object', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON object tracking what changed')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous field values')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New field values')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx'), models.Index(fields=['user', '-timestamp'], name='audit_log_user_id_79f582_idx'), models.Index(fields=['model_name', '-timestamp'], name='audit_log_model_n_1435ea_idx'), models.Index(fields=['operation', '-timestamp'], name='audit_log_operati_934dc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResearchAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_authorships', to=settings.AUTH_USER_MODEL)),
                ('id_research', models.ForeignKey(blank=True, db_column='id_research', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.research')),
            ],
            options={
                'db_table': 'research_author',
                'constraints': [models.UniqueConstraint(fields=('id_research', 'id_author'), name='unique_research_author_pair')],
            },
        ),
        migrations.CreateModel(
            name='SiteResearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_research', models.ForeignKey(db_column='id_research', on_delete=django.db.models.deletion.CASCADE, to='frontend.research')),
                ('id_site', models.ForeignKey(db_column='id_site', on_delete=django.db.models.deletion.CASCADE, to='frontend.site')),
            ],
            options={
                'db_table': 'site_research',
                'constraints': [models.UniqueConstraint(fields=('id_site', 'id_research'), name='unique_site_research_pair')],
            },
        ),
    ]
