# Generated by Django 5.0 on 2026-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_sitesettings_poster_lucretili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_partner_3_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
