services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: Open_Landscapes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  django:
    build:
      context: .
    container_name: shareland-django
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn ShareLand.wsgi:application -c gunicorn_config.py"
    volumes:
      - .:/app
      - static_volume:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_NAME: shareland_v1
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: "5432"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shareland-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shareland.it
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
    name: shareland_v10_postgres_data
  static_volume:
    name: shareland_static_volume
  pgadmin_data:
    name: shareland_v10_pgadmin_data
