# Generated by Django 5.2 on 2026-01-12 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('author', 'Author'), ('researcher', 'Researcher'), ('contributor', 'Contributor'), ('admin', 'Administrator'), ('moderator', 'Moderator')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this role', null=True)),
                ('permissions', models.TextField(blank=True, help_text='Comma-separated list of permissions (for reference)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_role',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('orcid', models.CharField(blank=True, help_text='ORCID ID (e.g., 0000-0000-0000-0000)', max_length=19, null=True, unique=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Alternative contact email for research/author purposes', max_length=254, null=True)),
                ('id_anagraphic', models.IntegerField(blank=True, help_text='Legacy anagraphic ID from imported data', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_roles', models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='profiles', to='users.userrole')),
            ],
        ),
    ]
